# Auth errors
AUTH_001 = "INVALID_CREDENTIALS"
AUTH_002 = "EMAIL_EXISTS"
AUTH_003 = "TOKEN_EXPIRED"

# Validation errors
VALIDATION_001 = "INVALID_INPUT"
VALIDATION_002 = "MISSING_FIELD"

# Not found errors
NOT_FOUND_001 = "USER_NOT_FOUND"
NOT_FOUND_002 = "CHAT_NOT_FOUND"
NOT_FOUND_003 = "PERSONA_NOT_FOUND"